repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3 # must match requirements_dev.txt
    hooks:
      - id: pycln
        args: [--config=pyproject.toml, src]
  - repo: https://github.com/psf/black
    rev: 23.1.0 # must match requirements_dev.txt
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # must match requirements_dev.txt
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # must match requirements_dev.txt
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-bugbear==23.3.12" # must match requirements_dev.txt
          - "flake8-noqa==1.3.0" # must match requirements_dev.txt
          - "flake8-pyi==23.1.2" # must match requirements_dev.txt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or: [yaml]

ci:
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [flake8]
  submodules: false
